version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_source_db
    networks:
      - chameleon_net
    ports:
      - "3306:3306"


  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    environment:
      - CB_SERVER_PORT=8978       # Standardport für CloudBeaver
      # Je nach Bedarf kannst du weitere Variablen setzen.
      # Siehe https://hub.docker.com/r/dbeaver/cloudbeaver
    ports:
      - "8978:8978"
    networks:
      - chameleon_net
    # Optional: Volume, wenn du z. B. Einstellungen persistent halten willst
    # volumes:
    #   - cloudbeaver_data:/opt/cloudbeaver/workspace


  pgchameleon:
    image: kivra/pg_chameleon:latest
    container_name: pg_chameleon
    # Wir mounten unsere lokale config.yaml nach /etc/pg_chameleon/config.yaml
    volumes:
      - ./config.yml:/etc/pg_chameleon/configuration/config.yml:ro    
    networks:
      - chameleon_net
    command: 
      - mkdir -p /root/pg_chameleon/logs
    # Kein Port-Mapping notwendig, da pg_chameleon nur CLI-Tools ausführt
    # Wenn du interaktiv Befehle absetzen möchtest, nutze z. B.:
    #   docker compose run pgchameleon <Befehl>
    # oder
    #   docker compose exec pgchameleon bash


  mongo:
    image: mongo:latest
    container_name: my_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=geheimespasswort
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - chameleon_net

  airbyte-db:
    image: postgres:13
    container_name: airbyte_db
    restart: always
    environment:
      - POSTGRES_USER=airbyte
      - POSTGRES_PASSWORD=airbyte
      - POSTGRES_DB=airbyte
    networks:
      - chameleon_net
    volumes:
      - airbyte_db_data:/var/lib/postgresql/data

  airbyte-server:
    image: airbyte/server:build-043b7cda49-21037-master
    container_name: airbyte_server
    restart: always
    depends_on:
      - airbyte-db
    ports:
      - "9090:8080"
    networks:
      - chameleon_net
    environment:
      - DATABASE_URL=jdbc:postgresql://airbyte-db:5432/airbyte
      - DATABASE_HOST=airbyte-db
      - DATABASE_PORT=5432
      - DATABASE_USER=airbyte
      - DATABASE_PASSWORD=airbyte  # 🔹 HIER FEHLTE DIE VARIABLE!
      - DATABASE_DB=airbyte
      - AIRBYTE_WORKSPACE_ROOT=/data/airbyte
      - AIRBYTE_DATABASE_HOST=airbyte-db
      - AIRBYTE_DATABASE_PORT=5432
      - AIRBYTE_DATABASE_USER=airbyte
      - AIRBYTE_DATABASE_PASSWORD=airbyte
      - AIRBYTE_DATABASE_DB=airbyte
    volumes:
      - airbyte_data:/data

  airbyte-webapp:
    image: airbyte/webapp:cloud-dev-dev-b0d57b2aaf
    container_name: airbyte_webapp
    restart: always
    depends_on:
      - airbyte-server
    ports:
      - "8000:8000"
    networks:
      - chameleon_net
    environment:
      - AIRBYTE_API_HOST=http://airbyte-server:9090
    volumes:
      - airbyte_data:/data

  airbyte-temporal:
    image: temporalio/auto-setup:latest
    container_name: airbyte-temporal
    restart: always
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - POSTGRES_USER=airbyte
      - POSTGRES_PASSWORD=airbyte
      - POSTGRES_HOST=airbyte-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=airbyte
    depends_on:
      - airbyte-db
    networks:
      - chameleon_net

volumes:
  mongo_data:
  airbyte_data:
  airbyte_db_data:

networks:
  chameleon_net:
    driver: bridge
