version: '3'
services:
  airflow:
    image: apache/airflow:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__WEBSERVER__SECRET_KEY=mysecretkey
    volumes:
      - ./airflow:/opt/airflow
      - ./dags:/opt/airflow/dags  # Hier wird dein DAG-Code in den Container gemountet
    command: ["standalone"]